pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
        maven { url "https://jitpack.io" }
        maven { url 'https://mirrors.tencent.com/nexus/repository/maven-public/' }
        maven { url "https://maven.aliyun.com/repository/public" }
        maven { url "https://maven.aliyun.com/nexus/content/repositories/jcenter" }
        maven { url "https://maven.aliyun.com/nexus/content/repositories/google" }
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url "https://jitpack.io" }
        maven { url 'https://mirrors.tencent.com/nexus/repository/maven-public/' }
        maven { url "https://maven.aliyun.com/repository/public" }
        maven { url "https://maven.aliyun.com/nexus/content/repositories/jcenter" }
        maven { url "https://maven.aliyun.com/nexus/content/repositories/google" }
    }
}

rootProject.name = "DebugAidl"
include ':app'
include ':aidl'
